#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaDal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PruebaTecnica")]
	public partial class ModeloFacturaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertFacturas(Facturas instance);
    partial void UpdateFacturas(Facturas instance);
    partial void DeleteFacturas(Facturas instance);
    partial void InsertProductoo(Productoo instance);
    partial void UpdateProductoo(Productoo instance);
    partial void DeleteProductoo(Productoo instance);
    #endregion
		
		public ModeloFacturaDataContext() : 
				base(global::FacturaDal.Properties.Settings.Default.PruebaTecnicaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloFacturaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloFacturaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloFacturaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloFacturaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Facturas> Facturas
		{
			get
			{
				return this.GetTable<Facturas>();
			}
		}
		
		public System.Data.Linq.Table<DetalleFactura> DetalleFactura
		{
			get
			{
				return this.GetTable<DetalleFactura>();
			}
		}
		
		public System.Data.Linq.Table<Productoo> Productoo
		{
			get
			{
				return this.GetTable<Productoo>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_creaDet")]
		public ISingleResult<sp_creaDetResult> sp_creaDet([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdFactura", DbType="Int")] System.Nullable<int> idFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ValorUnit", DbType="Int")] System.Nullable<int> valorUnit, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] System.Nullable<int> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura, idProducto, valorUnit, cantidad);
			return ((ISingleResult<sp_creaDetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_creaProducto")]
		public ISingleResult<sp_creaProductoResult> sp_creaProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Producto", DbType="VarChar(60)")] string producto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), producto);
			return ((ISingleResult<sp_creaProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_delDetalle")]
		public ISingleResult<sp_delDetalleResult> sp_delDetalle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdFactura", DbType="Int")] System.Nullable<int> idFactura)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura);
			return ((ISingleResult<sp_delDetalleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_delProducto")]
		public int sp_delProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_editFactura")]
		public ISingleResult<sp_editFacturaResult> sp_editFactura([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdFactura", DbType="Int")] System.Nullable<int> idFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroFactura", DbType="VarChar(20)")] string numeroFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipodePago", DbType="VarChar(30)")] string tipodePago, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(30)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(60)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Subtotal", DbType="Int")] System.Nullable<int> subtotal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descuento", DbType="Decimal(2,2)")] System.Nullable<decimal> descuento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IVA", DbType="Decimal(2,2)")] System.Nullable<decimal> iVA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalDescuento", DbType="Int")] System.Nullable<int> totalDescuento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalImpuesto", DbType="Int")] System.Nullable<int> totalImpuesto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Int")] System.Nullable<int> total)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura, numeroFactura, fecha, tipodePago, cedula, nombre, subtotal, descuento, iVA, totalDescuento, totalImpuesto, total);
			return ((ISingleResult<sp_editFacturaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_editProducto")]
		public int sp_editProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Producto", DbType="VarChar(60)")] string producto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, producto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getFacturas")]
		public ISingleResult<sp_getFacturasResult> sp_getFacturas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_getFacturasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getFactbyId")]
		public ISingleResult<sp_getFactbyIdResult> sp_getFactbyId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdFactura", DbType="Int")] System.Nullable<int> idFactura)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura);
			return ((ISingleResult<sp_getFactbyIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_delFactura")]
		public ISingleResult<sp_delFacturaResult> sp_delFactura([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdFactura", DbType="Int")] System.Nullable<int> idFactura)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idFactura);
			return ((ISingleResult<sp_delFacturaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_creaFactura")]
		public ISingleResult<sp_creaFacturaResult> sp_creaFactura([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroFactura", DbType="VarChar(20)")] string numeroFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipodePago", DbType="VarChar(30)")] string tipodePago, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(30)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(60)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Subtotal", DbType="Int")] System.Nullable<int> subtotal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descuento", DbType="Decimal(4,2)")] System.Nullable<decimal> descuento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IVA", DbType="Decimal(4,2)")] System.Nullable<decimal> iVA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalDescuento", DbType="Int")] System.Nullable<int> totalDescuento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalImpuesto", DbType="Int")] System.Nullable<int> totalImpuesto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Int")] System.Nullable<int> total)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numeroFactura, fecha, tipodePago, cedula, nombre, subtotal, descuento, iVA, totalDescuento, totalImpuesto, total);
			return ((ISingleResult<sp_creaFacturaResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Facturas")]
	public partial class Facturas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdFactura;
		
		private string _NumeroFactura;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _TipodePago;
		
		private string _DocumentoCliente;
		
		private string _NombreCliente;
		
		private System.Nullable<int> _Subtotal;
		
		private System.Nullable<decimal> _Descuento;
		
		private System.Nullable<decimal> _IVA;
		
		private System.Nullable<int> _TotalDescuento;
		
		private System.Nullable<int> _TotalImpuesto;
		
		private System.Nullable<int> _Total;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFacturaChanging(int value);
    partial void OnIdFacturaChanged();
    partial void OnNumeroFacturaChanging(string value);
    partial void OnNumeroFacturaChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnTipodePagoChanging(string value);
    partial void OnTipodePagoChanged();
    partial void OnDocumentoClienteChanging(string value);
    partial void OnDocumentoClienteChanged();
    partial void OnNombreClienteChanging(string value);
    partial void OnNombreClienteChanged();
    partial void OnSubtotalChanging(System.Nullable<int> value);
    partial void OnSubtotalChanged();
    partial void OnDescuentoChanging(System.Nullable<decimal> value);
    partial void OnDescuentoChanged();
    partial void OnIVAChanging(System.Nullable<decimal> value);
    partial void OnIVAChanged();
    partial void OnTotalDescuentoChanging(System.Nullable<int> value);
    partial void OnTotalDescuentoChanged();
    partial void OnTotalImpuestoChanging(System.Nullable<int> value);
    partial void OnTotalImpuestoChanged();
    partial void OnTotalChanging(System.Nullable<int> value);
    partial void OnTotalChanged();
    #endregion
		
		public Facturas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFactura", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdFactura
		{
			get
			{
				return this._IdFactura;
			}
			set
			{
				if ((this._IdFactura != value))
				{
					this.OnIdFacturaChanging(value);
					this.SendPropertyChanging();
					this._IdFactura = value;
					this.SendPropertyChanged("IdFactura");
					this.OnIdFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroFactura", DbType="VarChar(20)")]
		public string NumeroFactura
		{
			get
			{
				return this._NumeroFactura;
			}
			set
			{
				if ((this._NumeroFactura != value))
				{
					this.OnNumeroFacturaChanging(value);
					this.SendPropertyChanging();
					this._NumeroFactura = value;
					this.SendPropertyChanged("NumeroFactura");
					this.OnNumeroFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipodePago", DbType="VarChar(30)")]
		public string TipodePago
		{
			get
			{
				return this._TipodePago;
			}
			set
			{
				if ((this._TipodePago != value))
				{
					this.OnTipodePagoChanging(value);
					this.SendPropertyChanging();
					this._TipodePago = value;
					this.SendPropertyChanged("TipodePago");
					this.OnTipodePagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentoCliente", DbType="VarChar(30)")]
		public string DocumentoCliente
		{
			get
			{
				return this._DocumentoCliente;
			}
			set
			{
				if ((this._DocumentoCliente != value))
				{
					this.OnDocumentoClienteChanging(value);
					this.SendPropertyChanging();
					this._DocumentoCliente = value;
					this.SendPropertyChanged("DocumentoCliente");
					this.OnDocumentoClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCliente", DbType="VarChar(60)")]
		public string NombreCliente
		{
			get
			{
				return this._NombreCliente;
			}
			set
			{
				if ((this._NombreCliente != value))
				{
					this.OnNombreClienteChanging(value);
					this.SendPropertyChanging();
					this._NombreCliente = value;
					this.SendPropertyChanged("NombreCliente");
					this.OnNombreClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtotal", DbType="Int")]
		public System.Nullable<int> Subtotal
		{
			get
			{
				return this._Subtotal;
			}
			set
			{
				if ((this._Subtotal != value))
				{
					this.OnSubtotalChanging(value);
					this.SendPropertyChanging();
					this._Subtotal = value;
					this.SendPropertyChanged("Subtotal");
					this.OnSubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuento", DbType="Decimal(2,2)")]
		public System.Nullable<decimal> Descuento
		{
			get
			{
				return this._Descuento;
			}
			set
			{
				if ((this._Descuento != value))
				{
					this.OnDescuentoChanging(value);
					this.SendPropertyChanging();
					this._Descuento = value;
					this.SendPropertyChanged("Descuento");
					this.OnDescuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IVA", DbType="Decimal(2,2)")]
		public System.Nullable<decimal> IVA
		{
			get
			{
				return this._IVA;
			}
			set
			{
				if ((this._IVA != value))
				{
					this.OnIVAChanging(value);
					this.SendPropertyChanging();
					this._IVA = value;
					this.SendPropertyChanged("IVA");
					this.OnIVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDescuento", DbType="Int")]
		public System.Nullable<int> TotalDescuento
		{
			get
			{
				return this._TotalDescuento;
			}
			set
			{
				if ((this._TotalDescuento != value))
				{
					this.OnTotalDescuentoChanging(value);
					this.SendPropertyChanging();
					this._TotalDescuento = value;
					this.SendPropertyChanged("TotalDescuento");
					this.OnTotalDescuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalImpuesto", DbType="Int")]
		public System.Nullable<int> TotalImpuesto
		{
			get
			{
				return this._TotalImpuesto;
			}
			set
			{
				if ((this._TotalImpuesto != value))
				{
					this.OnTotalImpuestoChanging(value);
					this.SendPropertyChanging();
					this._TotalImpuesto = value;
					this.SendPropertyChanged("TotalImpuesto");
					this.OnTotalImpuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetalleFactura")]
	public partial class DetalleFactura
	{
		
		private System.Nullable<int> _IdFactura;
		
		private System.Nullable<int> _IdProducto;
		
		private System.Nullable<int> _ValorUnitario;
		
		private System.Nullable<int> _Cantidad;
		
		public DetalleFactura()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFactura", DbType="Int")]
		public System.Nullable<int> IdFactura
		{
			get
			{
				return this._IdFactura;
			}
			set
			{
				if ((this._IdFactura != value))
				{
					this._IdFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int")]
		public System.Nullable<int> IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorUnitario", DbType="Int")]
		public System.Nullable<int> ValorUnitario
		{
			get
			{
				return this._ValorUnitario;
			}
			set
			{
				if ((this._ValorUnitario != value))
				{
					this._ValorUnitario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Productoo")]
	public partial class Productoo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdProducto;
		
		private string _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdProductoChanging(int value);
    partial void OnIdProductoChanged();
    partial void OnProductoChanging(string value);
    partial void OnProductoChanged();
    #endregion
		
		public Productoo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this.OnIdProductoChanging(value);
					this.SendPropertyChanging();
					this._IdProducto = value;
					this.SendPropertyChanged("IdProducto");
					this.OnIdProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="VarChar(60)")]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this.OnProductoChanging(value);
					this.SendPropertyChanging();
					this._Producto = value;
					this.SendPropertyChanged("Producto");
					this.OnProductoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_creaDetResult
	{
		
		private System.Nullable<int> _Result;
		
		public sp_creaDetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int")]
		public System.Nullable<int> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class sp_creaProductoResult
	{
		
		private System.Nullable<int> _Result;
		
		public sp_creaProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int")]
		public System.Nullable<int> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class sp_delDetalleResult
	{
		
		private System.Nullable<int> _Result;
		
		public sp_delDetalleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int")]
		public System.Nullable<int> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class sp_editFacturaResult
	{
		
		private System.Nullable<int> _Result;
		
		public sp_editFacturaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int")]
		public System.Nullable<int> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class sp_getFacturasResult
	{
		
		private int _IdFactura;
		
		private string _NumeroFactura;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _TipodePago;
		
		private string _DocumentoCliente;
		
		private string _NombreCliente;
		
		private System.Nullable<int> _Subtotal;
		
		private System.Nullable<decimal> _Descuento;
		
		private System.Nullable<decimal> _IVA;
		
		private System.Nullable<int> _TotalDescuento;
		
		private System.Nullable<int> _TotalImpuesto;
		
		private System.Nullable<int> _Total;
		
		public sp_getFacturasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFactura", DbType="Int NOT NULL")]
		public int IdFactura
		{
			get
			{
				return this._IdFactura;
			}
			set
			{
				if ((this._IdFactura != value))
				{
					this._IdFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroFactura", DbType="VarChar(20)")]
		public string NumeroFactura
		{
			get
			{
				return this._NumeroFactura;
			}
			set
			{
				if ((this._NumeroFactura != value))
				{
					this._NumeroFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipodePago", DbType="VarChar(30)")]
		public string TipodePago
		{
			get
			{
				return this._TipodePago;
			}
			set
			{
				if ((this._TipodePago != value))
				{
					this._TipodePago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentoCliente", DbType="VarChar(30)")]
		public string DocumentoCliente
		{
			get
			{
				return this._DocumentoCliente;
			}
			set
			{
				if ((this._DocumentoCliente != value))
				{
					this._DocumentoCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCliente", DbType="VarChar(60)")]
		public string NombreCliente
		{
			get
			{
				return this._NombreCliente;
			}
			set
			{
				if ((this._NombreCliente != value))
				{
					this._NombreCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtotal", DbType="Int")]
		public System.Nullable<int> Subtotal
		{
			get
			{
				return this._Subtotal;
			}
			set
			{
				if ((this._Subtotal != value))
				{
					this._Subtotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuento", DbType="Decimal(2,2)")]
		public System.Nullable<decimal> Descuento
		{
			get
			{
				return this._Descuento;
			}
			set
			{
				if ((this._Descuento != value))
				{
					this._Descuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IVA", DbType="Decimal(2,2)")]
		public System.Nullable<decimal> IVA
		{
			get
			{
				return this._IVA;
			}
			set
			{
				if ((this._IVA != value))
				{
					this._IVA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDescuento", DbType="Int")]
		public System.Nullable<int> TotalDescuento
		{
			get
			{
				return this._TotalDescuento;
			}
			set
			{
				if ((this._TotalDescuento != value))
				{
					this._TotalDescuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalImpuesto", DbType="Int")]
		public System.Nullable<int> TotalImpuesto
		{
			get
			{
				return this._TotalImpuesto;
			}
			set
			{
				if ((this._TotalImpuesto != value))
				{
					this._TotalImpuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class sp_getFactbyIdResult
	{
		
		private int _IdFactura;
		
		private string _NumeroFactura;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _TipodePago;
		
		private string _DocumentoCliente;
		
		private string _NombreCliente;
		
		private System.Nullable<int> _Subtotal;
		
		private System.Nullable<decimal> _Descuento;
		
		private System.Nullable<decimal> _IVA;
		
		private System.Nullable<int> _TotalDescuento;
		
		private System.Nullable<int> _TotalImpuesto;
		
		private System.Nullable<int> _Total;
		
		public sp_getFactbyIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFactura", DbType="Int NOT NULL")]
		public int IdFactura
		{
			get
			{
				return this._IdFactura;
			}
			set
			{
				if ((this._IdFactura != value))
				{
					this._IdFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroFactura", DbType="VarChar(20)")]
		public string NumeroFactura
		{
			get
			{
				return this._NumeroFactura;
			}
			set
			{
				if ((this._NumeroFactura != value))
				{
					this._NumeroFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipodePago", DbType="VarChar(30)")]
		public string TipodePago
		{
			get
			{
				return this._TipodePago;
			}
			set
			{
				if ((this._TipodePago != value))
				{
					this._TipodePago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentoCliente", DbType="VarChar(30)")]
		public string DocumentoCliente
		{
			get
			{
				return this._DocumentoCliente;
			}
			set
			{
				if ((this._DocumentoCliente != value))
				{
					this._DocumentoCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCliente", DbType="VarChar(60)")]
		public string NombreCliente
		{
			get
			{
				return this._NombreCliente;
			}
			set
			{
				if ((this._NombreCliente != value))
				{
					this._NombreCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtotal", DbType="Int")]
		public System.Nullable<int> Subtotal
		{
			get
			{
				return this._Subtotal;
			}
			set
			{
				if ((this._Subtotal != value))
				{
					this._Subtotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descuento", DbType="Decimal(2,2)")]
		public System.Nullable<decimal> Descuento
		{
			get
			{
				return this._Descuento;
			}
			set
			{
				if ((this._Descuento != value))
				{
					this._Descuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IVA", DbType="Decimal(2,2)")]
		public System.Nullable<decimal> IVA
		{
			get
			{
				return this._IVA;
			}
			set
			{
				if ((this._IVA != value))
				{
					this._IVA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDescuento", DbType="Int")]
		public System.Nullable<int> TotalDescuento
		{
			get
			{
				return this._TotalDescuento;
			}
			set
			{
				if ((this._TotalDescuento != value))
				{
					this._TotalDescuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalImpuesto", DbType="Int")]
		public System.Nullable<int> TotalImpuesto
		{
			get
			{
				return this._TotalImpuesto;
			}
			set
			{
				if ((this._TotalImpuesto != value))
				{
					this._TotalImpuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class sp_delFacturaResult
	{
		
		private System.Nullable<int> _Result;
		
		public sp_delFacturaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int")]
		public System.Nullable<int> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class sp_creaFacturaResult
	{
		
		private int _IdFactura;
		
		public sp_creaFacturaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFactura", DbType="Int NOT NULL")]
		public int IdFactura
		{
			get
			{
				return this._IdFactura;
			}
			set
			{
				if ((this._IdFactura != value))
				{
					this._IdFactura = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
